<a href="https://colab.research.google.com/github/Huhhuu/DataDeepLearning/blob/main/Tuan_1_THDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dự Án Phân Tích Dữ Liệu Xét Tuyển Đại Học

Quy trình này thực hiện các bước tiền xử lý dữ liệu để chuẩn bị cho mô hình Deep Learning.

In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

# 1. Tạo cấu trúc thư mục lưu trữ
dirs = ['data/raw', 'data/processed']
for d in dirs:
    os.makedirs(d, exist_ok=True)

print("Đã tạo các thư mục:", dirs)

Đã tạo các thư mục: ['data/raw', 'data/processed']

### 2. Tải và Khám phá dữ liệu
Chúng ta sẽ tải dữ liệu trực tiếp từ GitHub và lưu bản thô vào thư mục `data/raw`.

In [2]:
url = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/dulieuxettuyendaihoc.csv'
df = pd.read_csv(url)

# Lưu trữ bản thô
df.to_csv('data/raw/raw_data.csv', index=False)

print("Thông tin sơ bộ về dữ liệu:")
display(df.info())
display(df.head())

Thông tin sơ bộ về dữ liệu:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STT     100 non-null    int64
 1   T1      100 non-null    float64
 2   L1      100 non-null    float64
 3   H1      100 non-null    float64
 4   S1      100 non-null    float64
 5   V1      100 non-null    float64
 6   X1      100 non-null    float64
 7   D1      100 non-null    float64
 8   N1      100 non-null    float64
 9   T2      100 non-null    float64
 10  L2      100 non-null    float64
 11  H2      100 non-null    float64
 12  S2      100 non-null    float64
 13  V2      100 non-null    float64
 14  X2      100 non-null    float64
 15  D2      100 non-null    float64
 16  N2      100 non-null    float64
 17  T3      100 non-null    float64
 18  L3      100 non-null    float64
 19  H3      100 non-null    float64
 20  S3      100 non-null    float64
 21  V3      100 non-null    float64
 22  X3      100 non-null    float64
 23  D3      100 non-null    float64
 24  N3      100 non-null    float64
 25  T4      100 non-null    float64
 26  L4      100 non-null    float64
 27  H4      100 non-null    float64
 28  S4      100 non-null    float64
 29  V4      100 non-null    float64
 30  X4      100 non-null    float64
 31  D4      100 non-null    float64
 32  N4      100 non-null    float64
 33  T5      100 non-null    float64
 34  L5      100 non-null    float64
 35  H5      100 non-null    float64
 36  S5      100 non-null    float64
 37  V5      100 non-null    float64
 38  X5      100 non-null    float64
 39  D5      100 non-null    float64
 40  N5      100 non-null    float64
 41  T6      100 non-null    float64
 42  L6      100 non-null    float64
 43  H6      100 non-null    float64
 44  S6      100 non-null    float64
 45  V6      100 non-null    float64
 46  X6      100 non-null    float64
 47  D6      100 non-null    float64
 48  N6      100 non-null    float64
 49  GT      100 non-null    object
 50  DT      3 non-null      float64
 51  KV      100 non-null    object
 52  DH1     100 non-null    float64
 53  DH2     100 non-null    float64
 54  DH3     100 non-null    float64
 55  KT      100 non-null    object
dtypes: float64(52), int64(1), object(3)
memory usage: 43.9+ KB

None

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A

### 3. Làm sạch dữ liệu
Bước này tập trung vào việc xử lý các giá trị rỗng (NaN) và chuyển đổi các cột dữ liệu phù hợp.

In [3]:
import pandas as pd
import numpy as np

# Kiểm tra và xử lý giá trị thiếu
df = df.fillna(df.median(numeric_only=True))

# One-Hot Encoding cho các cột phân loại
categorical_cols = df.select_dtypes(include=['object']).columns
df = pd.get_dummies(df, columns=categorical_cols)

print("Dữ liệu sau khi làm sạch và mã hóa:")
display(df.head())
print(f"Tổng số giá trị thiếu còn lại: {df.isnull().sum().sum()}")

Dữ liệu sau khi làm sạch và mã hóa:

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,GT_F,GT_M,KV_1,KV_2,KV_2NT,KT_A,KT_A1,KT_B,KT_C,KT_D1
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,True,False,False,False,True,False,True,False,False,False
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,False,True,True,False,False,False,False,False,True,False
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,False,True,True,False,False,False,False,False,True,False
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,False,True,True,False,False,False,False,False,False,True
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,False,True,False,False,True,True,False,False,False,False

Tổng số giá trị thiếu còn lại: 0

### 3.1 Chuyển đổi dữ liệu phân loại (One-Hot Encoding)
Trong Deep Learning, các cột dạng chữ (như Khu vực, Dân tộc) cần được chuyển sang dạng số. One-Hot Encoding sẽ tạo ra các cột 0/1 tương ứng với từng phân loại.

In [4]:
# Xác định các cột không phải dạng số (object/category)
categorical_cols = df.select_dtypes(include=['object']).columns
print(f"Các cột sẽ được mã hóa: {list(categorical_cols)}")

# Thực hiện One-Hot Encoding
df_encoded = pd.get_dummies(df, columns=categorical_cols)

# Cập nhật lại df chính để dùng cho các bước sau
df = df_encoded

print("Kích thước dữ liệu sau khi mã hóa:", df.shape)
display(df.head())

Các cột sẽ được mã hóa: []
Kích thước dữ liệu sau khi mã hóa: (100, 63)

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,GT_F,GT_M,KV_1,KV_2,KV_2NT,KT_A,KT_A1,KT_B,KT_C,KT_D1
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,True,False,False,False,True,False,True,False,False,False
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,False,True,True,False,False,False,False,False,True,False
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,False,True,True,False,False,False,False,False,True,False
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,False,True,True,False,False,False,False,False,False,True
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,False,True,False,False,True,True,False,False,False,False

### 3.2 Kiểm tra lại giá trị thiếu sau mã hóa
Đảm bảo rằng quá trình xử lý không để lại giá trị rỗng nào.

In [5]:
final_missing_check = df.isnull().sum().sum()
print(f"Tổng số giá trị thiếu còn lại: {final_missing_check}")

if final_missing_check > 0:
    print("Các cột vẫn còn giá trị thiếu:")
    display(df.columns[df.isnull().any()].tolist())
else:
    print("Dữ liệu đã sạch hoàn toàn.")

Tổng số giá trị thiếu còn lại: 0
Dữ liệu đã sạch hoàn toàn.

### 4. Chia tập Train và Test
Thông thường chúng ta chia theo tỷ lệ 80% Train và 20% Test.

In [6]:
# Chia dữ liệu
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

# Lưu vào thư mục processed
train_df.to_csv('data/processed/train.csv', index=False)
test_df.to_csv('data/processed/test.csv', index=False)

print(f"Kích thước tập Train: {train_df.shape}")
print(f"Kích thước tập Test: {test_df.shape}")
print("Dữ liệu đã sẵn sàng trong thư mục 'data/processed/'")

Kích thước tập Train: (80, 63)
Kích thước tập Test: (20, 63)
Dữ liệu đã sẵn sàng trong thư mục 'data/processed/'

### Lưu trữ data trên Google Drive

In [11]:
from google.colab import drive
import os

# 1. Kết nối (Mount) với Google Drive
drive.mount('/content/drive')

# 2. Tạo thư mục dự án trên Drive
drive_path = '/content/drive/MyDrive/du_an_th_deep_learning'
os.makedirs(drive_path, exist_ok=True)

# 3. Lưu dữ liệu đã xử lý vào Drive
train_df.to_csv(f'{drive_path}/train_processed.csv', index=False)
test_df.to_csv(f'{drive_path}/test_processed.csv', index=False)

print(f"Dữ liệu đã được lưu tại: {drive_path}")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dữ liệu đã được lưu tại: /content/drive/MyDrive/du_an_th_deep_learning

### 5. Kiểm tra kiểu dữ liệu cuối cùng
Trước khi đưa vào mô hình Deep Learning, tất cả các đặc trưng (features) phải ở dạng số.

In [7]:
print("Kiểm tra thông tin cuối cùng của tập huấn luyện:")
train_df.info()

# Xác nhận không còn dữ liệu dạng chuỗi
non_numeric = train_df.select_dtypes(exclude=[np.number, 'bool']).columns
if len(non_numeric) == 0:
    print("\n=> Tất cả dữ liệu đã sẵn sàng (đều là dạng số).")

Kiểm tra thông tin cuối cùng của tập huấn luyện:
<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 55 to 51
Data columns (total 63 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STT     80 non-null     int64
 1   T1      80 non-null     float64
 2   L1      80 non-null     float64
 3   H1      80 non-null     float64
 4   S1      80 non-null     float64
 5   V1      80 non-null     float64
 6   X1      80 non-null     float64
 7   D1      80 non-null     float64
 8   N1      80 non-null     float64
 9   T2      80 non-null     float64
 10  L2      80 non-null     float64
 11  H2      80 non-null     float64
 12  S2      80 non-null     float64
 13  V2      80 non-null     float64
 14  X2      80 non-null     float64
 15  D2      80 non-null     float64
 16  N2      80 non-null     float64
 17  T3      80 non-null     float64
 18  L3      80 non-null     float64
 19  H3      80 non-null     float64
 20  S3      80 non-null     float64
 21  V3      80 non-null     float64
 22  X3      80 non-null     float64
 23  D3      80 non-null     float64
 24  N3      80 non-null     float64
 25  T4      80 non-null     float64
 26  L4      80 non-null     float64
 27  H4      80 non-null     float64
 28  S4      80 non-null     float64
 29  V4      80 non-null     float64
 30  X4      80 non-null     float64
 31  D4      80 non-null     float64
 32  N4      80 non-null     float64
 33  T5      80 non-null     float64
 34  L5      80 non-null     float64
 35  H5      80 non-null     float64
 36  S5      80 non-null     float64
 37  V5      80 non-null     float64
 38  X5      80 non-null     float64
 39  D5      80 non-null     float64
 40  N5      80 non-null     float64
 41  T6      80 non-null     float64
 42  L6      80 non-null     float64
 43  H6      80 non-null     float64
 44  S6      80 non-null     float64
 45  V6      80 non-null     float64
 46  X6      80 non-null     float64
 47  D6      80 non-null     float64
 48  N6      80 non-null     float64
 49  DT      80 non-null     float64
 50  DH1     80 non-null     float64
 51  DH2     80 non-null     float64
 52  DH3     80 non-null     float64
 53  GT_F    80 non-null     bool
 54  GT_M    80 non-null     bool
 55  KV_1    80 non-null     bool
 56  KV_2    80 non-null     bool
 57  KV_2NT  80 non-null     bool
 58  KT_A    80 non-null     bool
 59  KT_A1   80 non-null     bool
 60  KT_B    80 non-null     bool
 61  KT_C    80 non-null     bool
 62  KT_D1   80 non-null     bool
dtypes: bool(10), float64(52), int64(1)
memory usage: 34.5 KB

=> Tất cả dữ liệu đã sẵn sàng (đều là dạng số).

In [8]:
print("Thông tin chi tiết về tập train_df:")
train_df.info()

Thông tin chi tiết về tập train_df:
<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 55 to 51
Data columns (total 63 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STT     80 non-null     int64
 1   T1      80 non-null     float64
 2   L1      80 non-null     float64
 3   H1      80 non-null     float64
 4   S1      80 non-null     float64
 5   V1      80 non-null     float64
 6   X1      80 non-null     float64
 7   D1      80 non-null     float64
 8   N1      80 non-null     float64
 9   T2      80 non-null     float64
 10  L2      80 non-null     float64
 11  H2      80 non-null     float64
 12  S2      80 non-null     float64
 13  V2      80 non-null     float64
 14  X2      80 non-null     float64
 15  D2      80 non-null     float64
 16  N2      80 non-null     float64
 17  T3      80 non-null     float64
 18  L3      80 non-null     float64
 19  H3      80 non-null     float64
 20  S3      80 non-null     float64
 21  V3      80 non-null     float64
 22  X3      80 non-null     float64
 23  D3      80 non-null     float64
 24  N3      80 non-null     float64
 25  T4      80 non-null     float64
 26  L4      80 non-null     float64
 27  H4      80 non-null     float64
 28  S4      80 non-null     float64
 29  V4      80 non-null     float64
 30  X4      80 non-null     float64
 31  D4      80 non-null     float64
 32  N4      80 non-null     float64
 33  T5      80 non-null     float64
 34  L5      80 non-null     float64
 35  H5      80 non-null     float64
 36  S5      80 non-null     float64
 37  V5      80 non-null     float64
 38  X5      80 non-null     float64
 39  D5      80 non-null     float64
 40  N5      80 non-null     float64
 41  T6      80 non-null     float64
 42  L6      80 non-null     float64
 43  H6      80 non-null     float64
 44  S6      80 non-null     float64
 45  V6      80 non-null     float64
 46  X6      80 non-null     float64
 47  D6      80 non-null     float64
 48  N6      80 non-null     float64
 49  DT      80 non-null     float64
 50  DH1     80 non-null     float64
 51  DH2     80 non-null     float64
 52  DH3     80 non-null     float64
 53  GT_F    80 non-null     bool
 54  GT_M    80 non-null     bool
 55  KV_1    80 non-null     bool
 56  KV_2    80 non-null     bool
 57  KV_2NT  80 non-null     bool
 58  KT_A    80 non-null     bool
 59  KT_A1   80 non-null     bool
 60  KT_B    80 non-null     bool
 61  KT_C    80 non-null     bool
 62  KT_D1   80 non-null     bool
dtypes: bool(10), float64(52), int64(1)
memory usage: 34.5 KB