<a href="https://colab.research.google.com/github/Huhhuu/DataDeepLearning/blob/main/Tuan_1_THDeepLearning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Dự Án Phân Tích Dữ Liệu Xét Tuyển Đại Học

Quy trình này thực hiện các bước tiền xử lý dữ liệu để chuẩn bị cho mô hình Deep Learning.

In [6]:
import os
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

dirs = ['data/raw', 'data/processed']
for d in dirs:
    os.makedirs(d, exist_ok=True)

print("Đã tạo các thư mục:", dirs)

Đã tạo các thư mục: ['data/raw', 'data/processed']

### 2. Tải và Khám phá dữ liệu
Chúng ta sẽ tải dữ liệu trực tiếp từ GitHub và lưu bản thô vào thư mục `data/raw`.

In [7]:
url = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/dulieuxettuyendaihoc.csv'
df = pd.read_csv(url)

df.to_csv('data/raw/raw_data.csv', index=False)

print("Thông tin sơ bộ về dữ liệu:")
display(df.info())
display(df.head())

Thông tin sơ bộ về dữ liệu:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 56 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   STT     100 non-null    int64
 1   T1      100 non-null    float64
 2   L1      100 non-null    float64
 3   H1      100 non-null    float64
 4   S1      100 non-null    float64
 5   V1      100 non-null    float64
 6   X1      100 non-null    float64
 7   D1      100 non-null    float64
 8   N1      100 non-null    float64
 9   T2      100 non-null    float64
 10  L2      100 non-null    float64
 11  H2      100 non-null    float64
 12  S2      100 non-null    float64
 13  V2      100 non-null    float64
 14  X2      100 non-null    float64
 15  D2      100 non-null    float64
 16  N2      100 non-null    float64
 17  T3      100 non-null    float64
 18  L3      100 non-null    float64
 19  H3      100 non-null    float64
 20  S3      100 non-null    float64
 21  V3      100 non-null    float64
 22  X3      100 non-null    float64
 23  D3      100 non-null    float64
 24  N3      100 non-null    float64
 25  T4      100 non-null    float64
 26  L4      100 non-null    float64
 27  H4      100 non-null    float64
 28  S4      100 non-null    float64
 29  V4      100 non-null    float64
 30  X4      100 non-null    float64
 31  D4      100 non-null    float64
 32  N4      100 non-null    float64
 33  T5      100 non-null    float64
 34  L5      100 non-null    float64
 35  H5      100 non-null    float64
 36  S5      100 non-null    float64
 37  V5      100 non-null    float64
 38  X5      100 non-null    float64
 39  D5      100 non-null    float64
 40  N5      100 non-null    float64
 41  T6      100 non-null    float64
 42  L6      100 non-null    float64
 43  H6      100 non-null    float64
 44  S6      100 non-null    float64
 45  V6      100 non-null    float64
 46  X6      100 non-null    float64
 47  D6      100 non-null    float64
 48  N6      100 non-null    float64
 49  GT      100 non-null    object
 50  DT      3 non-null      float64
 51  KV      100 non-null    object
 52  DH1     100 non-null    float64
 53  DH2     100 non-null    float64
 54  DH3     100 non-null    float64
 55  KT      100 non-null    object
dtypes: float64(52), int64(1), object(3)
memory usage: 43.9+ KB

None

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A

### Phân loại dữ liệu và Xác định thang đo
- **Dữ liệu định tính (Qualitative):** `GT` (Nominal), `KV` (Nominal), `KT` (Nominal), `DT` (Nominal).
- **Dữ liệu định lượng (Quantitative):** `T1..T6`, `L1..L6`, `H1..H6`, `S1..S6`, `V1..V6`, `X1..X6`, `D1..D6`, `N1..N6` (Ratio), `DH1..DH3` (Ratio).

In [8]:
import pandas as pd
import numpy as np

url = 'https://raw.githubusercontent.com/huynhhoc/DataAnalystDeepLearning/refs/heads/main/Data/dulieuxettuyendaihoc.csv'
df = pd.read_csv(url)

print("10 dòng đầu tiên:")
display(df.head(10))
print("\n10 dòng cuối cùng:")
display(df.tail(10))

10 dòng đầu tiên:

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
5,6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
6,7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
7,8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
8,9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
9,10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

10 dòng cuối cùng:

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
90,91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
91,92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
92,93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
93,94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
94,95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

### Xử lý dữ liệu thiếu
- Cột `DT` (Dân tộc): Điền 0.
- Các cột điểm số: Điền giá trị trung bình (Mean).

In [9]:
print("Tần số giá trị unique cột DT trước xử lý:", df['DT'].unique())
df['DT'] = df['DT'].fillna(0)

print(f"Số lượng missing T1: {df['T1'].isnull().sum()}")
df['T1'] = df['T1'].fillna(df['T1'].mean())

score_cols = ['T1','L1','H1','S1','V1','X1','D1','N1','T2','L2','H2','S2','V2','X2','D2','N2','T3','L3','H3','S3','V3','X3','D3','N3','T4','L4','H4','S4','V4','X4','D4','N4','T5','L5','H5','S5','V5','X5','D5','N5','T6','L6','H6','S6','V6','X6','D6','N6','DH1','DH2','DH3']
for col in score_cols:
    df[col] = df[col].fillna(df[col].mean())

print("Tổng missing value sau xử lý:", df.isnull().sum().sum())

Tần số giá trị unique cột DT trước xử lý: [nan  1.  6.]
Số lượng missing T1: 0
Tổng missing value sau xử lý: 0

### Tính toán TBM, Xếp loại, và Quy đổi thang điểm Mỹ

In [10]:
for i in range(1, 4):
    df[f'TBM{i}'] = (df[f'T{i}']*2 + df[f'L{i}'] + df[f'H{i}'] + df[f'S{i}'] + df[f'V{i}']*2 + df[f'X{i}'] + df[f'D{i}'] + df[f'N{i}']) / 10

def xep_loai(diem):
    if diem < 5.0: return 'Y'
    elif diem < 6.5: return 'TB'
    elif diem < 8.0: return 'K'
    elif diem < 9.0: return 'G'
    else: return 'XS'

for i in range(1, 4):
    df[f'XL{i}'] = df[f'TBM{i}'].apply(xep_loai)

for i in range(1, 4):
    min_val, max_val = df[f'TBM{i}'].min(), df[f'TBM{i}'].max()
    df[f'US_TBM{i}'] = ((df[f'TBM{i}'] - min_val) / (max_val - min_val)) * 4

display(df[['TBM1', 'XL1', 'US_TBM1']].head())

   TBM1 XL1   US_TBM1
0  7.00   K  2.930693
1  4.69   Y  0.643564
2  5.77  TB  1.712871
3  6.21  TB  2.148515
4  6.50   K  2.435644

### Kết quả xét tuyển (KQXT)
Tính toán dựa trên tổ hợp môn của từng khối thi.

In [11]:
def tinh_kqxt(row):
    kt = row['KT']
    dh1, dh2, dh3 = row['DH1'], row['DH2'], row['DH3']

    if kt in ['A', 'A1']:
        diem = (dh1*2 + dh2 + dh3) / 4
    elif kt == 'B':
        diem = (dh1 + dh2*2 + dh3) / 4
    else:
        diem = (dh1 + dh2 + dh3) / 3

    return 1 if diem >= 5.0 else 0

df['KQXT'] = df.apply(tinh_kqxt, axis=1)
print("Số lượng thí sinh Đậu (1) và Rớt (0):")
print(df['KQXT'].value_counts())

Số lượng thí sinh Đậu (1) và Rớt (0):
KQXT
0    88
1    12
Name: count, dtype: int64

In [5]:
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)
print("Đã lưu file: processed_dulieuxettuyendaihoc.csv")

Đã lưu file: processed_dulieuxettuyendaihoc.csv

### 3. Làm sạch dữ liệu
Bước này tập trung vào việc xử lý các giá trị rỗng (NaN) và chuyển đổi các cột dữ liệu phù hợp.

In [12]:
import pandas as pd
import numpy as np

categorical_cols = df.select_dtypes(include=['object']).columns
df = pd.get_dummies(df, columns=categorical_cols)

for col in df.select_dtypes(include=['bool']).columns:
    df[col] = df[col].astype(int)

print("Dữ liệu sau khi làm sạch và mã hóa:")
display(df.head())
print(f"Tổng số giá trị thiếu còn lại: {df.isnull().sum().sum()}")

Dữ liệu sau khi làm sạch và mã hóa:

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,XL1_TB,XL1_Y,XL2_G,XL2_K,XL2_TB,XL2_Y,XL3_G,XL3_K,XL3_TB,XL3_Y
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,0,0,0,1,0,0,0,1,0,0
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,0,1,0,0,1,0,0,0,0,1
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,1,0,0,0,1,0,0,0,0,1
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,1,0,0,0,1,0,0,0,1,0
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,0,0,0,0,1,0,0,1,0,0

Tổng số giá trị thiếu còn lại: 0

### 3.1 Kiểm tra lại giá trị thiếu sau mã hóa
Đảm bảo rằng quá trình xử lý không để lại giá trị rỗng nào.

In [14]:
final_missing_check = df.isnull().sum().sum()
print(f"Tổng số giá trị thiếu còn lại: {final_missing_check}")

if final_missing_check > 0:
    print("Các cột vẫn còn giá trị thiếu:")
    display(df.columns[df.isnull().any()].tolist())
else:
    print("Dữ liệu đã sạch hoàn toàn.")

Tổng số giá trị thiếu còn lại: 0
Dữ liệu đã sạch hoàn toàn.

### 4. Chia tập Train và Test
Thông thường chúng ta chia theo tỷ lệ 80% Train và 20% Test.

In [15]:
train_df, test_df = train_test_split(df, test_size=0.2, random_state=42)

train_df.to_csv('data/processed/train.csv', index=False)
test_df.to_csv('data/processed/test.csv', index=False)

print(f"Kích thước tập Train: {train_df.shape}")
print(f"Kích thước tập Test: {test_df.shape}")
print("Dữ liệu đã sẵn sàng trong thư mục 'data/processed/'")

Kích thước tập Train: (80, 82)
Kích thước tập Test: (20, 82)
Dữ liệu đã sẵn sàng trong thư mục 'data/processed/'

### Lưu trữ data trên Google Drive

In [16]:
from google.colab import drive
import os

drive.mount('/content/drive')

drive_path = '/content/drive/MyDrive/du_an_th_deep_learning'
os.makedirs(drive_path, exist_ok=True)

train_df.to_csv(f'{drive_path}/train_processed.csv', index=False)
test_df.to_csv(f'{drive_path}/test_processed.csv', index=False)

print(f"Dữ liệu đã được lưu tại: {drive_path}")

Mounted at /content/drive
Dữ liệu đã được lưu tại: /content/drive/MyDrive/du_an_th_deep_learning

### 5. Kiểm tra kiểu dữ liệu cuối cùng
Trước khi đưa vào mô hình Deep Learning, tất cả các đặc trưng (features) phải ở dạng số.

In [17]:
print("Kiểm tra thông tin cuối cùng của tập huấn luyện:")
train_df.info()

non_numeric = train_df.select_dtypes(exclude=[np.number, 'bool']).columns
if len(non_numeric) == 0:
    print("\n=> Tất cả dữ liệu đã sẵn sàng (đều là dạng số).")

Kiểm tra thông tin cuối cùng của tập huấn luyện:
<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 55 to 51
Data columns (total 82 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STT      80 non-null     int64
 1   T1       80 non-null     float64
 2   L1       80 non-null     float64
 3   H1       80 non-null     float64
 4   S1       80 non-null     float64
 5   V1       80 non-null     float64
 6   X1       80 non-null     float64
 7   D1       80 non-null     float64
 8   N1       80 non-null     float64
 9   T2       80 non-null     float64
 10  L2       80 non-null     float64
 11  H2       80 non-null     float64
 12  S2       80 non-null     float64
 13  V2       80 non-null     float64
 14  X2       80 non-null     float64
 15  D2       80 non-null     float64
 16  N2       80 non-null     float64
 17  T3       80 non-null     float64
 18  L3       80 non-null     float64
 19  H3       80 non-null     float64
 20  S3       80 non-null     float64
 21  V3       80 non-null     float64
 22  X3       80 non-null     float64
 23  D3       80 non-null     float64
 24  N3       80 non-null     float64
 25  T4       80 non-null     float64
 26  L4       80 non-null     float64
 27  H4       80 non-null     float64
 28  S4       80 non-null     float64
 29  V4       80 non-null     float64
 30  X4       80 non-null     float64
 31  D4       80 non-null     float64
 32  N4       80 non-null     float64
 33  T5       80 non-null     float64
 34  L5       80 non-null     float64
 35  H5       80 non-null     float64
 36  S5       80 non-null     float64
 37  V5       80 non-null     float64
 38  X5       80 non-null     float64
 39  D5       80 non-null     float64
 40  N5       80 non-null     float64
 41  T6       80 non-null     float64
 42  L6       80 non-null     float64
 43  H6       80 non-null     float64
 44  S6       80 non-null     float64
 45  V6       80 non-null     float64
 46  X6       80 non-null     float64
 47  D6       80 non-null     float64
 48  N6       80 non-null     float64
 49  DT       80 non-null     float64
 50  DH1      80 non-null     float64
 51  DH2      80 non-null     float64
 52  DH3      80 non-null     float64
 53  TBM1     80 non-null     float64
 54  TBM2     80 non-null     float64
 55  TBM3     80 non-null     float64
 56  US_TBM1  80 non-null     float64
 57  US_TBM2  80 non-null     float64
 58  US_TBM3  80 non-null     float64
 59  KQXT     80 non-null     int64
 60  GT_F     80 non-null     int64
 61  GT_M     80 non-null     int64
 62  KV_1     80 non-null     int64
 63  KV_2     80 non-null     int64
 64  KV_2NT   80 non-null     int64
 65  KT_A     80 non-null     int64
 66  KT_A1    80 non-null     int64
 67  KT_B     80 non-null     int64
 68  KT_C     80 non-null     int64
 69  KT_D1    80 non-null     int64
 70  XL1_G    80 non-null     int64
 71  XL1_K    80 non-null     int64
 72  XL1_TB   80 non-null     int64
 73  XL1_Y    80 non-null     int64
 74  XL2_G    80 non-null     int64
 75  XL2_K    80 non-null     int64
 76  XL2_TB   80 non-null     int64
 77  XL2_Y    80 non-null     int64
 78  XL3_G    80 non-null     int64
 79  XL3_K    80 non-null     int64
 80  XL3_TB   80 non-null     int64
 81  XL3_Y    80 non-null     int64
dtypes: float64(58), int64(24)
memory usage: 51.9 KB

=> Tất cả dữ liệu đã sẵn sàng (đều là dạng số).

In [18]:
print("Thông tin chi tiết về tập train_df:")
train_df.info()

Thông tin chi tiết về tập train_df:
<class 'pandas.core.frame.DataFrame'>
Index: 80 entries, 55 to 51
Data columns (total 82 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   STT      80 non-null     int64
 1   T1       80 non-null     float64
 2   L1       80 non-null     float64
 3   H1       80 non-null     float64
 4   S1       80 non-null     float64
 5   V1       80 non-null     float64
 6   X1       80 non-null     float64
 7   D1       80 non-null     float64
 8   N1       80 non-null     float64
 9   T2       80 non-null     float64
 10  L2       80 non-null     float64
 11  H2       80 non-null     float64
 12  S2       80 non-null     float64
 13  V2       80 non-null     float64
 14  X2       80 non-null     float64
 15  D2       80 non-null     float64
 16  N2       80 non-null     float64
 17  T3       80 non-null     float64
 18  L3       80 non-null     float64
 19  H3       80 non-null     float64
 20  S3       80 non-null     float64
 21  V3       80 non-null     float64
 22  X3       80 non-null     float64
 23  D3       80 non-null     float64
 24  N3       80 non-null     float64
 25  T4       80 non-null     float64
 26  L4       80 non-null     float64
 27  H4       80 non-null     float64
 28  S4       80 non-null     float64
 29  V4       80 non-null     float64
 30  X4       80 non-null     float64
 31  D4       80 non-null     float64
 32  N4       80 non-null     float64
 33  T5       80 non-null     float64
 34  L5       80 non-null     float64
 35  H5       80 non-null     float64
 36  S5       80 non-null     float64
 37  V5       80 non-null     float64
 38  X5       80 non-null     float64
 39  D5       80 non-null     float64
 40  N5       80 non-null     float64
 41  T6       80 non-null     float64
 42  L6       80 non-null     float64
 43  H6       80 non-null     float64
 44  S6       80 non-null     float64
 45  V6       80 non-null     float64
 46  X6       80 non-null     float64
 47  D6       80 non-null     float64
 48  N6       80 non-null     float64
 49  DT       80 non-null     float64
 50  DH1      80 non-null     float64
 51  DH2      80 non-null     float64
 52  DH3      80 non-null     float64
 53  TBM1     80 non-null     float64
 54  TBM2     80 non-null     float64
 55  TBM3     80 non-null     float64
 56  US_TBM1  80 non-null     float64
 57  US_TBM2  80 non-null     float64
 58  US_TBM3  80 non-null     float64
 59  KQXT     80 non-null     int64
 60  GT_F     80 non-null     int64
 61  GT_M     80 non-null     int64
 62  KV_1     80 non-null     int64
 63  KV_2     80 non-null     int64
 64  KV_2NT   80 non-null     int64
 65  KT_A     80 non-null     int64
 66  KT_A1    80 non-null     int64
 67  KT_B     80 non-null     int64
 68  KT_C     80 non-null     int64
 69  KT_D1    80 non-null     int64
 70  XL1_G    80 non-null     int64
 71  XL1_K    80 non-null     int64
 72  XL1_TB   80 non-null     int64
 73  XL1_Y    80 non-null     int64
 74  XL2_G    80 non-null     int64
 75  XL2_K    80 non-null     int64
 76  XL2_TB   80 non-null     int64
 77  XL2_Y    80 non-null     int64
 78  XL3_G    80 non-null     int64
 79  XL3_K    80 non-null     int64
 80  XL3_TB   80 non-null     int64
 81  XL3_Y    80 non-null     int64
dtypes: float64(58), int64(24)
memory usage: 51.9 KB